### ISSUE TITLE
Queries only return the first 10000 rows due to paging.

### ISSUE THREAD

**Issue by greigs** [neuecc/LINQ-to-BigQuery#33]
BigQuery splits pages of results into 10000 by default, regardless of MaxResults. 
I have modified the code to allow result set pages to be combined when the result size is > 10000.
The commit is here: https://github.com/greigs/LINQ-to-BigQuery/commit/fced9060853e7b27bfdb8cba34d64a3d706afa81

**Comment by greigs** [comment]
More information about this: http://stackoverflow.com/a/14807770/1102234

**Comment by neuecc** [comment]
Thank you!
I'll check soon.

**Comment by neuecc** [comment]
Sorry for extreme lated.
I've added.

**Comment by neuecc** [comment]
Today I released 0.6.1 and its included.
