### ISSUE TITLE
Doesn't work with latest version of BigQuery (1.9.2.2240)

### ISSUE THREAD

**Issue by privlin** [neuecc/LINQ-to-BigQuery#36]
![linqtobigquerynotworking](https://cloud.githubusercontent.com/assets/891402/9108441/c3059eda-3c36-11e5-9024-53a50dde7382.jpg)

**Comment by neuecc** [comment]
Oh, it's ciritcal!
Thank you, I'll check tomorrow and fix as soon as possible.

**Comment by neuecc** [comment]
Today I released 0.6.1, dependency is `1.9.2.2240`.
