### ISSUE TITLE
Linqpad settings

### ISSUE THREAD

**Issue by naveensrinivasan** [neuecc/LINQ-to-BigQuery#43]
I am trying to use this in LinqPad. 

What should go in the Json Authentication Key? Is it the file? 

What should go in the User textbox?

It would help if there is some writeup on this.

Thank you!

**Comment by neuecc** [comment]
Hi, thank you for try to use.

JSON Authentication Key is here.

![image](https://cloud.githubusercontent.com/assets/46207/11946366/68337f76-a89d-11e5-887f-ee9e324638ac.png)

![image](https://cloud.githubusercontent.com/assets/46207/11946372/7e0df4f2-a89d-11e5-86e5-f990d7ba6f06.png)

Download JSON and copy/paste text key.

User is your mail address of GCP.

**Comment by naveensrinivasan** [comment]
Thank you! This would help in the README.

**Comment by sammy1188** [comment]
Hi..can you advise which key? I'm assuming it's the private_key but is not accepting it. I'm not sure what you mean by text key, there is no text key for the json credentials
